"""Recreate processed_requests table

Revision ID: 959e300864f0
Revises: e5060646f464
Create Date: 2025-05-03 17:02:58.629782

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "959e300864f0"
down_revision: Union[str, None] = "e5060646f464"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
